# **Python102: Python for Data Science Bootcamp**
**Tutorial 3.3 (T3_3)  - NumPy Operation (Part 3)**

# NumPy Operations

## Arithmetic

(การคำนวณทางคณิตศาสตร์ด้วย NumPy)

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [0]:
import numpy as np
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
print(array + array)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [0]:
array * array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
# Warning on division by zero, but not an error!
# Just replaced with nan
array/array

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
# Also warning, but not an error instead infinity
1/array

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [0]:
# ** ยกกำลัง
array**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

(NumPy มีฟงก์ชั่นการคำนวณทางคณิตศาสตร์มากมายที่สามารถนำมาใช้กับโปรเจคต่างๆได้อย่างครอบคลุม)

In [0]:
#Taking Square Roots
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
#Calcualting exponential (e^)
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [0]:
print(np.max(array))
print(array.max())

9
9


In [0]:
np.sin(array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [0]:
np.log(array)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])