# **Python102: Python for Data Science Bootcamp**
**Tutorial 3.2 (T3_2)  - NumPy Indexing and Selection (Part 2)**





# NumPy Indexing and Selection

การเข้าถึงอาเรย์ของ NumPy

In [0]:
import numpy as np

In [0]:
#Creating sample array (สร้าง Array)
array = np.arange(0,11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:
(วิธีการเข้าถึงค่าใน Element ของ NumPy Arrays จะคล้ายกับ List ของ Python)

In [0]:
#Get a value at an index
array[5]

5

In [0]:
#Get values in a range (Slicing)
print(array[1:6])
print(array[0:6])

[1 2 3 4 5]
[0 1 2 3 4 5]


## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

การกระจายค่าเข้าไปใน NumPy Arrays

In [0]:
#Setting a value with index range (Broadcasting)
array[0:5]=100
print(array)

[100 100 100 100 100   5   6   7   8   9  10]


In [0]:
# Reset array
array = np.arange(0,11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [0]:
#Important notes on Slices
slice_of_array = array[0:6]
print(slice_of_array)

[0 1 2 3 4 5]


In [0]:
#Change Slice

slice_of_array[:]=99
print(slice_of_array)

[99 99 99 99 99 99]


Now note the changes also occur in our original array!

การเปลี่ยนค่าของ Elements ใน บางส่วนของ Array ใหม่ (**slice_of_array**) จะเปลี่ยนค่า Original อง Array (**array**) นั้นด้วย

In [0]:
print(array)

[99 99 99 99 99 99  6  7  8  9 10]


Data is not copied, it's a view of the original array! This avoids memory problems!

ซึ่งหมายความว่า Python ไม่ได้ Copy ค่าจาก Original Array มาใส่ที่ ตัวแปรใหม่ (ตัวแปรใหม่ (**slice_of_array**) ยังมี Address ในการเก็บข้อมูลเดียวกันกับ Original Array  (**array**))

In [0]:
#To get a copy, need to be explicit
array_copy = array.copy()
print(array_copy)

[99 99 99 99 99 99  6  7  8  9 10]


## Indexing a 2D array (matrices)

การเข้าถึง อาเรย์ 2 มิติ

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. 

In [0]:
array_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
print(array_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [0]:
#Indexing row 
# เข้าถึงแถวที่ 1 Note: Index เริ่มจาก 0
print(array_2d[1])


[20 25 30]


In [0]:
# Format is array_2d[row][col] or array_2d[row,col]
# Getting individual element value
print(array_2d[1][0])

20


In [0]:
# Getting individual element value
print(array_2d[1,0])

20


In [0]:
# 2D array slicing
#Shape (2,2) from top right corner
print(array_2d[:2,1:])

[[10 15]
 [25 30]]


In [0]:
#Shape bottom row
print(array_2d[2])

[35 40 45]


In [0]:
#Shape bottom row
print(array_2d[2,:])

[35 40 45]


### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [0]:
#Set up matrix
array2d = np.zeros((10,10))

In [0]:
#Length of array
array_length = array2d.shape[1]
print(array_length)

10


In [0]:
#Set up array

for i in range(array_length):
    array2d[i] = i
    
print(array2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


Fancy indexing allows the following

In [0]:
array2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [0]:
#Allows in any order
array2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [0]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
array > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_array = array>4

In [0]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
array[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
array[array>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
x = 2
array[array>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])